SELECT
	SKU,
	NAME As PRODUCT_NAME,
	TYPE As PRODUCT_TYPE,
    PRICE As UNIT_PRICE,
    DESCRIPTION As PRODUCT_DESCRIPTION,
    _AIRBYTE_EXTRACTED_AT As LOADED_AT
FROM {{ source('jaffle_shop', 'jaffle_products') }}