name: dbt Pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: write

env:
  snowflake_pass: ${{ secrets.SNOWFLAKE_PASS }}
  
jobs:
  dbt-project-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dbt
      run: pip install dbt-snowflake
    - name: Run dbt
      env:
        snowflake_pass: ${{ secrets.SNOWFLAKE_PASS }}
        snowflake_user: ${{ secrets.SNOWFLAKE_USER }}
        snowflake_account: ${{ secrets.SNOWFLAKE_ACCT }}
        snowflake_wh: ${{ secrets.SNOWFLAKE_WH }}
      run: |
        mkdir /home/runner/.dbt
        echo "This is my current working directory=$( pwd )"
        cp ./jaffle_shop/profiles.yml /home/runner/.dbt/
        export snowflake_pass=${{ secrets.SNOWFLAKE_PASS }}
        dbt deps --project-dir ./jaffle_shop --vars 'custom_db: mds_prod'
        dbt run --project-dir ./jaffle_shop --vars 'custom_db: mds_prod'
        dbt test --project-dir ./jaffle_shop --vars 'custom_db: mds_prod'
        dbt docs generate --project-dir ./jaffle_shop --vars 'custom_db: mds_prod'
        cp -r ./jaffle_shop/target/* ./Docs/
    - name: Deploy dbt docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: jaffle_shop/target
    - name: Upload run_results.json
      uses: actions/upload-artifact@v4
      with:
        name: dbt-run-results
        path: ./jaffle_shop/target/run_results.json
    - name: Upload manifest.json
      uses: actions/upload-artifact@v4
      with:
        name: dbt-manifest
        path: ./jaffle_shop/target/manifest.json
    - name: Upload catalog.json
      uses: actions/upload-artifact@v4
      with:
        name: dbt-catalog
        path: ./jaffle_shop/target/catalog.json
    - name: Upload graph_summary.json
      uses: actions/upload-artifact@v4
      with:
        name: dbt-graph_summary
        path: ./jaffle_shop/target/graph_summary.json
    - name: Upload index.html
      uses: actions/upload-artifact@v4
      with:
        name: dbt-index
        path: ./jaffle_shop/target/index.html
    - name: Download artifacts
      uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R