name: dbt Pipeline
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

env:
  snowflake_pass: ${{ secrets.SNOWFLAKE_PASS }}
  
jobs:
  dbt-project-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dbt
      run: pip install dbt-snowflake
    - name: Run dbt
      env:
        snowflake_pass: ${{ secrets.SNOWFLAKE_PASS }}
        snowflake_user: ${{ secrets.SNOWFLAKE_USER }}
        snowflake_acct: ${{ secrets.SNOWFLAKE_ACCT }}
        snowflake_wh: ${{ secrets.SNOWFLAKE_WH }}
      run: |
        mkdir /home/runner/.dbt
        echo "This is my current working directory=$( pwd )"
        cp ./profiles.yml /home/runner/.dbt/
        export snowflake_pass=${{ secrets.SNOWFLAKE_PASS }}
        dbt deps --project-dir . --vars '{"custom_db":"mds_prod", "custom_schema": "", "stg_schema":"STAGING", "int_schema":"INTERMEDIATE", "mart_schema":"MART"}' --target prod
        dbt run --project-dir . --vars '{"custom_db":"mds_prod", "custom_schema": "", "stg_schema":"STAGING", "int_schema":"INTERMEDIATE", "mart_schema":"MART"}' --target prod
        dbt test --project-dir . --vars '{"custom_db":"mds_prod", "custom_schema": "", "stg_schema":"STAGING", "int_schema":"INTERMEDIATE", "mart_schema":"MART"}' --target prod
        dbt docs generate --project-dir . --vars '{"custom_db":"mds_prod", "custom_schema": "", "stg_schema":"STAGING", "int_schema":"INTERMEDIATE", "mart_schema":"MART"}' --target prod
    - name: Commit manifest.json
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        git add target/manifest.json
        git commit -m "Update manifest.json after dbt run" || echo "No changes to commit"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
    - name: Deploy dbt docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target
    - name: Upload run_results.json
      uses: actions/upload-artifact@v4
      with:
        name: dbt-run-results
        path: ./target/run_results.json
    - name: Upload manifest.json
      uses: actions/upload-artifact@v4
      with:
        name: dbt-manifest
        path: ./target/manifest.json
    - name: Upload catalog.json
      uses: actions/upload-artifact@v4
      with:
        name: dbt-catalog
        path: ./target/catalog.json
    - name: Upload graph_summary.json
      uses: actions/upload-artifact@v4
      with:
        name: dbt-graph_summary
        path: ./target/graph_summary.json
    - name: Upload index.html
      uses: actions/upload-artifact@v4
      with:
        name: dbt-index
        path: ./target/index.html
    - name: Download artifacts
      uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R