on:
  pull_request:
    branches: [main]

jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    env:
      DBT_PR_SCHEMA: _pr_${{ github.event.pull_request.number }}
      snowflake_pass: ${{ secrets.SNOWFLAKE_PASS }}
      snowflake_user: ${{ secrets.SNOWFLAKE_USER }}
      snowflake_acct: ${{ secrets.SNOWFLAKE_ACCT }}
      snowflake_wh: ${{ secrets.SNOWFLAKE_WH }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Install dbt and deps
        run: |
          pip install dbt-snowflake
          dbt deps --vars '{"custom_db":"mds_prod", "custom_schema": "'$DBT_PR_SCHEMA'"}' --target prod

      - name: Get manifest from main for state comparison
        run: |
          mkdir /home/runner/.dbt
          cp ./profiles.yml /home/runner/.dbt/
          git fetch origin main
          git checkout origin/main -- target/manifest.json
          echo "This is the target directory=$( ls target/ )"
          cp target/manifest.json /home/runner/.dbt/
          cp target/manifest.json .

      - name: Build impacted models
        run: |
          changed_models=$(dbt ls --select state:modified --state . \
          --vars '{"custom_db":"mds_prod", "custom_schema":"'$DBT_PR_SCHEMA'"}' --target prod --resource-type model \
          | grep '^jaffle_shop' | sed "s/.*/'&'/" | paste -sd, - | sed 's/^/[/;s/$/]/')
          dbt run --models state:modified+ --state . --vars '{"custom_db":"mds_prod", "custom_schema":"'$DBT_PR_SCHEMA'", "selected_models":"'$changed_models'"}' --target prod
